{{- if and .Values.agentController.enabled .Values.agentController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gastown.agentController.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gastown.agentController.labels" . | nindent 4 }}
  {{- with .Values.agentController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
